#!/usr/bin/perl

$foot = .00000274;
$bucket = 5280 * $foot;
$pi = 4 * atan2(1, 1);

open(IN, "names-corrected-centers");
while (<IN>) {
	# 60390 Powell PL bart-home-3-07.svg bart-other-2-08.svg 37.784050,-122.407565

	next if /#/;

	chomp;
	($riders, $name, $code, $where) = split(/ /, $_, 4);
	while ($where =~ s/.*svg //) {
		;
	}
	($lat, $lon) = split(/,/, $where);

	$name{$code} = $name;
	$lat{$code} = $lat;
	$lon{$code} = $lon;
	$riders{$code} = $riders;

	push @{$cand{int($lat / $bucket)}{int($lon / $bucket)}}, $code;
}
close(IN);

open(IN, "Ridership_May2015.csv");
$_ = <IN>;
$_ = <IN>;
@stations = split(/,/, $_);
while (<IN>) {
	@fields = split(/,/);
	last if $fields[0] eq "Entries";
	for ($i = 1; $i <= $#fields; $i++) {
		last if $stations[$i] eq "Exits";

		if ($fields[0] lt $stations[$i]) {
			$name = "$fields[0]-$stations[$i]";
		} else {
			$name = "$stations[$i]-$fields[0]";
		}

		$count{$name} += $fields[$i];
	}
}

sub find {
	my ($lat, $lon) = @_;

	if ($distance{$lat}{$lon} ne "") {
		return ($station{$lat}{$lon}, $distance{$lat}{$lon});
	}

	my $best = "";
	my $bestd = 4 * 5280;
	my $rat = cos($lat * $pi / 180);

	my ($a, $o);
	for ($a = int($lat / $bucket) - 4; $a <= int($lat / $bucket) + 4; $a++) {
		for ($o = int($lon / $bucket) - 4; $o <= int($lon / $bucket) + 4; $o++) {
			my @cand = @{$cand{$a}{$o}};

			for my $c (@cand) {
				my $latd = $lat - $lat{$c};
				my $lond = ($lon - $lon{$c}) * $rat;
				my $d = sqrt($latd * $latd + $lond * $lond) / $foot;

				if ($d < $bestd) {
					$bestd = $d;
					$best = $c;
				}
			}
		}
	}

	$station{$lat}{$lon} = $best;
	$distance{$lat}{$lon} = $bestd;

	return ($best, $bestd);
}

sub pdf {
	my ($x, $u, $o) = @_;

	return exp(- ((log($x) - $u) * (log($x) - $u) / 2 * $o * $o)) / ($x * $o * sqrt(2 * $pi));
}

open(IN, "all-commute-2012-37-122");
while (<IN>) {
	$s = int($seq++ * 100 / 4211586);
	if ($s != $os) {
		$os = $s;
		print STDERR "$s\r";
	}

	chomp;
	@fields = split(/,/);

	$count = $fields[2];
	$worklat = $fields[13];
	$worklon = $fields[14];
	$homelat = $fields[15];
	$homelon = $fields[16];

	($workstation, $workdistance) = find($worklat, $worklon);
	($homestation, $homedistance) = find($homelat, $homelon);

	$workweight = pdf($workdistance, 7.13947, 1.03404) / $workdistance;
	$homeweight = pdf($homedistance, 8.64499, 1.20751) / $homedistance;

	if ($workstation ne "" && $homestation ne "") {
		if ($workstation le $homestation) {
			$weight{"$workstation-$homestation"} += $workweight * $homeweight * $count;
		} else {
			$weight{"$homestation-$workstation"} += $workweight * $homeweight * $count;
		}
	}

	if ($workstation ne "" && $homestation ne "") {
		$val = 1.00174e+09 * exp(log($workweight * $homeweight * $count) * 0.549674);
		$sum{$homestation} += $val;
		$sum{$workstation} += $val;
	}
}

# f(x) = m * x ** a
# fit log(f(x)) "assigned" using 2:(log($3)) via m, a

if (1) {
	for $station (sort(keys(%sum))) {
		next if $station eq "";

		printf("%s %.16f %d %d\n", $name{$station}, $sum{$station}, $riders{$station}, 3.28502 * exp(log($sum{$station}) * 0.660321));
	}

	exit(0);
}

for $pair (sort(keys(%weight))) {
	printf("%s %.32f %d\n", $pair, $weight{$pair}, $count{$pair});
}
